Control8/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("reviewer.urls")),
        path("auth/", include('accounts.urls')),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

reviewer/urls.py
from django.urls import path

from reviewer.views.base import IndexView, IndexRedirectView
from reviewer.views.categories import categories_list, category
from reviewer.views.products import *
from reviewer.views.reviews import ReviewCreateView, ReviewDetailView, ReviewDeleteView, ReviewUpdateView


app_name = "reviewer"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("product/", IndexRedirectView.as_view(), name="products_index_redirect"),
    path("product/create", ProductCreateView.as_view(), name="product_create"),
    path("product/<int:pk>", ProductDetail.as_view(), name="product_detail"),
    path(
        "product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"
    ),
    path(
        "product/<int:pk>/confirm_delete/",
        ProductDeleteView.as_view(),
        name="product_confirm_delete",
    ),
    path("category/", categories_list, name="categories_list"),
    path("products/<pk>", category, name="category"),
    path("product/<int:pk>/review/add", ReviewCreateView.as_view(), name="review_create"),
    path("review/<pk>", ReviewDetailView.as_view(), name="review_detail"),
    path(
        "review/<int:pk>/update/", ReviewUpdateView.as_view(), name="review_update"
    ),
    path(
        "review/<int:pk>/delete/", ReviewDeleteView.as_view(), name="review_delete"
    ),
    path(
        "review/<int:pk>/confirm_delete/",
        ReviewDeleteView.as_view(),
        name="review_confirm_delete",
    ),

]

reviewer/models/products.py
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import TextChoices
from django.utils import timezone


class CategoryChoice(TextChoices):
    OTHER = "other", "Other"
    FOOD = "food", "Food"
    PHARMACY = "pharmacy", "Pharmacy"
    CAR = "car", "Car"
    DEVICE = "device", "Device"


class Product(models.Model):
    title = models.CharField(
        max_length=100, null=False, blank=False, verbose_name="Title"
    )
    category = models.TextField(
        max_length=40,
        choices=CategoryChoice.choices,
        verbose_name="Category",
        default=CategoryChoice.OTHER,
        blank=False,
    )
    description = models.TextField(
        max_length=2000,
        null=True,
        blank=True,
        verbose_name="Description",
        default="No Description",
    )
    image = models.TextField(
        max_length=2000, null=True, blank=True, verbose_name="Image",
        default="https://icon-library.com/images/none-icon/none-icon-1.jpg"
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Date and time created"
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Date and time updated"
    )
    is_deleted = models.BooleanField(verbose_name="Deleted", null=False, default=False)
    deleted_at = models.DateTimeField(
        verbose_name="Date and time deleted at", null=True, default=None
    )

    def __str__(self):
        return self.title

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

reviewer/models/reviews.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

from reviewer.manager import ReviewManager


class Review(models.Model):
    author = models.ForeignKey(
        User,
        verbose_name="Автор",
        related_name="reviews",
        null=False,
        blank=False,
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        verbose_name="Товар",
        to="Product",
        related_name="reviews",
        null=False,
        blank=False,
        on_delete=models.CASCADE,
    )
    text = models.TextField(
        verbose_name="Комментарий", null=False, blank=False, max_length=20000
    )
    grade = models.IntegerField(
        null=False,
        blank=False,
        verbose_name="Grade",
        validators=[MinValueValidator(0), MaxValueValidator(5)],
        default=None,
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Date and time created"
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Date and time updated"
    )
    is_deleted = models.BooleanField(verbose_name="Deleted", null=False, default=False)
    deleted_at = models.DateTimeField(
        verbose_name="Date and time deleted at", null=True, default=None
    )
    objects = ReviewManager()

    def __str__(self):
        return self.text[:15]

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

reviewer/forms.py
from django import forms
from django.core.exceptions import ValidationError

from reviewer.models import Product, Review


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["title", "category", "image", "description"]

    def clean_title(self):
        title = self.cleaned_data.get("title")
        if len(title) < 2:
            raise ValidationError("Title must be longer than two characters!")
        return title


class SimpleSearchForm(forms.Form):
    search = forms.CharField(
        max_length=30,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search Product...",
                "style": "border: solid #da7b93 2px; font-size: 16px; position: absolute;",
            }
        ),
    )


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            "text",
            "grade"
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["text"].widget.attrs.update({"placeholder": "Добавьте отзыв...", "style": "width: 90%;"})
        self.fields["grade"].widget.attrs.update({"placeholder": "Введите оценку от 1 до 5"})
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "review-box"
            visible.label = ""

reviewer/views/apps.py
from django.apps import AppConfig


class ReviewerAppConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "reviewer"

reviewer/views/base.py
from django.db.models import Q, Avg
from django.utils.http import urlencode
from django.views.generic import RedirectView, ListView

from reviewer.forms import SimpleSearchForm
from reviewer.models import Product, Review


class IndexView(ListView):
    template_name = "products/index.html"
    model = Product
    context_object_name = "products"
    ordering = ("created_at",)
    paginate_by = 6
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data["search"]
        return None

    def get_queryset(self):
        queryset = (
            super()
            .get_queryset()
            .filter(is_deleted=False)
            .order_by("category", "title")
        )
        if self.search_value:
            query = Q(title__icontains=self.search_value) | Q(
                description__icontains=self.search_value
            )
            queryset = queryset.filter(query)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        context["products_with_avg"] = Product.objects.filter(reviews__grade__gt=0)\
            .annotate(avg_grade=Avg("reviews__grade"))
        if self.search_value:
            context["query"] = urlencode({"search": self.search_value})
        return context


class IndexRedirectView(RedirectView):
    pattern_name = "index"

reviewer/views/categories.py
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render

from reviewer.forms import SimpleSearchForm
from reviewer.models import CategoryChoice, Product


def categories_list(request: WSGIRequest):
    form = SimpleSearchForm()
    title = request.GET.get("title")
    if title:
        products = (
            Product.objects.all()
            .filter(is_deleted=False, balance__gte=0, title=title)
            .order_by("category", "title")
        )
        context = {
            "products": products,
            "choices": CategoryChoice.choices,
            "form": form,
        }
        return render(request, "products/index.html", context=context)
    else:
        context = {"choices": CategoryChoice.choices, "form": form}
        return render(request, "categories/categories.html", context=context)


def category(request, pk):
    form = SimpleSearchForm()
    products = Product.objects.filter(is_deleted=False, category=pk)
    products.order_by("category", "title").values()
    if not products:
        message = f"You have no products in category {pk}"
        context = {"message": message, "form": form}
    else:
        message = f"You have {len(products)} product in category {pk}"
        context = {
            "products": products,
            "choices": CategoryChoice.choices,
            "message": message,
            "form": form,
        }
    return render(request, "products/index.html", context=context)

reviewer/views/products.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    TemplateView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from reviewer.forms import ProductForm, ReviewForm
from reviewer.models import Product, CategoryChoice, Review


class ProductDetail(DetailView):
    template_name = "products/product.html"
    model = Product
    form_class = ReviewForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reviews_ = Review.objects.filter(product_id=self.object.pk, is_deleted=False)
        products = Product.objects.filter(id=self.object.pk)
        context["products"] = products
        context["choices"] = CategoryChoice.choices
        context["form"] = self.form_class
        context["reviews"] = reviews_
        return context


class ProductCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "products/product_create.html"
    model = Product
    form_class = ProductForm
    success_message = "Товар добавлен"

    def get_success_url(self):
        return reverse("product_detail", kwargs={"pk": self.object.pk})


class ProductUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = "products/product_update.html"
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse("product_detail", kwargs={"pk": self.object.pk})


class ProductDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    template_name = "products/product_confirm_delete.html"
    model = Product
    success_url = reverse_lazy("index")


class ProductConfirmDeleteView(LoginRequiredMixin, SuccessMessageMixin, TemplateView):
    template_name = "products/product_confirm_delete.html"
    success_message = "Товар удален"

    def post(self, request, **kwargs):
        context = super().get_context_data(**kwargs)
        context["product"] = get_object_or_404(Product, pk=kwargs["pk"])
        context["product"].delete()
        return redirect("index")

reviewer/views/reviews.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, TemplateView

from reviewer.forms import ReviewForm
from reviewer.models import Review, Product


class ReviewCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "products/product.html"
    model = Review
    form_class = ReviewForm
    success_message = "Отзыв добавлен"

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get("pk"))
        review = form.save(commit=False)
        review.post = product
        review.author = self.request.user
        review.save()
        return redirect('reviewer:product_detail', pk=product.pk)


class ReviewDetailView(DetailView):
    template_name = 'reviews/review.html'
    model = Review

    def get_success_url(self):
        return reverse("reviewer:review_detail", kwargs={"pk": self.object.pk})


class ReviewUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = "reviews/review_update.html"
    model = Review
    form_class = ReviewForm
    success_message = "Отзыв обновлен"

    def get_success_url(self):
        return reverse("reviewer:review_detail", kwargs={"pk": self.object.pk})


class ReviewDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    template_name = "reviews/review_confirm_delete.html"
    model = Review
    success_url = reverse_lazy("reviewer:index")


class ReviewConfirmDeleteView(LoginRequiredMixin, SuccessMessageMixin, TemplateView):
    template_name = "reviews/review_confirm_delete.html"
    success_message = "Отзыв удален"

    def post(self, request, **kwargs):
        context = super().get_context_data(**kwargs)
        context["review"] = get_object_or_404(Review, pk=kwargs["pk"])
        context["review"].delete()
        return redirect("reviewer:index")

reviewer/templates/products/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block menu %}
    {% include 'partial/product_search_in_menu.html' %}
{% endblock %}
{% block content %}
    <div class="message-box">
        <p class="msg">{{ message }}</p>
    </div>
    <div class="content">
        <div class="card-group">
            {% for product in products %}
                {% include 'partial/product_card.html' with footer='products' %}
            {% endfor %}
        </div>
        <div class="paginator-box">
            {% if is_paginated %}
                {% include 'partial/pagination.html' %}
            {% endif %}
        </div>
    </div>
{% endblock %}

reviewer/templates/products/product.html
{% extends 'base.html' %}
{% block title %}Product{% endblock %}
{% block content %}
    <div class="content">
        {% include 'partial/product_card.html' with footer='product' %}
    </div>
{% endblock %}

reviewer/templates/products/product_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Product delete{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    <div class="content">
        <h2 class="delete-text">Are sure to delete this product?</h2>
        {% include 'partial/product_card.html' with footer='delete' %}
    </div>
{% endblock %}

reviewer/templates/products/product_create.html
{% extends 'base.html' %}
{% block title %}Product Create{% endblock %}
{% block content %}
    <div class="form-box">
        <h1>Add new product</h1>
        <div class="form">
            <form action="{% url 'reviewer:product_create' %}" method="post">
                {% include 'partial/product_form.html' with button_text='Add Product' button_class='btn btn-outline-dark btn-lg' %}
            </form>
        </div>
    </div>
{% endblock %}

reviewer/templates/products/product_update.html
{% extends 'base.html' %}
{% block title %}product Update{% endblock %}
{% block content %}
    <div class="form-box">
        <h1>Edit</h1>
        <div class="form">
            <form action="{% url 'reviewer:product_update' product.id %}" method="post">
                {% include 'partial/product_form.html' with button_text='SEND' button_class='btn btn-outline-dark btn-lg' %}
            </form>
        </div>
    </div>
{% endblock %}

reviewer/templates/products/products_delete.html
{% extends 'base.html' %}
{% block title %}Products to Delete{% endblock %}
{% block content %}
    <div class="table-box form-box card-shadow">
        <form action="{% url 'reviewer:products_delete' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col" class="th-style">#</th>
                    <th scope="col" class="th-style">Title</th>
                    <th scope="col" class="th-style">Category</th>
                    <th scope="col" class="th-style">Price</th>
                    <th scope="col" class="th-style">Balance</th>
                </tr>
                </thead>
                <tbody>
                {% for product in products %}
                    <tr>
                        <th scope="row">
                            <label for="check"></label>
                            <input type="checkbox" name="{{ product.pk }}" id="check">
                        </th>
                        <td>{{ product.title }}</td>
                        <td>{% include 'partial/product_category.html' with style='' %}</td>
                        <td>{{ product.price }}</td>
                        <td>{{ product.balance }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <input type="submit" class="btn btn-outline-dark" value="Delete">
        </form>
    </div>
{% endblock %}