Control8/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("reviewer.urls")),
        path("auth/", include('accounts.urls')),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

accounts/urls.py
from django.urls import path

from accounts.views import (
    LoginView,
    logout_view,
    RegisterView,
    UserDetailView, UserChangeView,
)

app_name = "accounts"


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/<int:pk>", UserDetailView.as_view(), name='detail'),
    path("profile/<int:pk>/change", UserChangeView.as_view(), name='change'),
]

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model


class LoginForm(forms.Form):
    username = forms.CharField(required=True, label="Логин")
    password = forms.CharField(
        required=True, label="Пароль", widget=forms.PasswordInput
    )


class CustomUserCreationForm(forms.ModelForm):
    password = forms.CharField(
        label="Пароль", strip=False, required=True, widget=forms.PasswordInput
    )
    password_confirm = forms.CharField(
        label="Подтвердите пароль",
        strip=False,
        required=True,
        widget=forms.PasswordInput,
    )
    email = forms.EmailField(required=True, label="Email")

    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "first_name",
            "email",
            "password",
            "password_confirm",
        )

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Пароли не совпадают!")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get("password"))
        # user.groups.add("user")
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["first_name", "email"]
        labels = {"first_name": "Имя", "email": "Email"}

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView
from accounts.forms import (
    LoginForm,
    CustomUserCreationForm, UserChangeForm,
)


class LoginView(TemplateView):
    template_name = 'login.html'
    form = LoginForm

    def get(self, request, *args, **kwargs):
        form = self.form()
        context = {'form': form}
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if not form.is_valid():
            messages.error(request, 'Некорректная форма')
            return redirect('reviewer:index')
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if not user:
            messages.warning(request, 'Пользователь не найден')
            return redirect('reviewer:index')
        login(request, user)
        messages.success(request, 'Добро пожаловать')
        next = request.GET.get('next')
        if next:
            return redirect(next)
        return redirect('reviewer:index')


def logout_view(request):
    logout(request)
    return redirect("reviewer:index")


class RegisterView(CreateView):
    template_name = "register.html"
    form_class = CustomUserCreationForm
    success_url = "/"

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(self.success_url)
        context = {"form": form}
        return self.render_to_response(context)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 5
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        reviews = self.object.reviews.order_by('-created_at')
        paginator = Paginator(reviews, self.paginate_related_by, orphans=self.paginate_related_orphans)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['reviews'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class UserChangeView(UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        response = super().form_valid(form)
        form.save()
        return response

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return UserChangeForm(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})

accounts/templates/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="form-box">
        <form method="post">
            <div class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
            </div>
            <div class="form_row">
                {% bootstrap_button button_type="submit" content='Войти' %}
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/register.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="form-box">
        <form method="post">
            <div class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
            </div>
            <div class="form_row">
                {% bootstrap_button button_type="submit" content='Зарегестрироваться' %}
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/user_change.html
{% extends 'base.html' %}
{% block title %}Редактировать пользователя{% endblock %}
{% block menu_links %}
    <li><a href="{% url "profile" user_obj.pk %}">Назад</a></li>
    <li><a href="#">Смена пароля</a></li>
{% endblock %}
{% block content %}
    <h1>Поменять личные данные</h1>
    <form action="{% url 'change' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input type="submit" value="Редактировать">
    </form>
{% endblock %}

accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}Пользователь{% endblock %}

{% block menu %}
    <li><a href="{% url 'accounts:change' user_obj.pk %}" class="btn btn-primary">Редактировать</a></li>
{% endblock %}

{% block content %}
    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
    {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
    {% endif %}
    <p>Логин: {{ user_obj.username }}</p>
    <p>Имя: {{ user_obj.first_name }}</p>
    <p>Почта: {{ user_obj.email }}</p>

    <h2 class="text-center clear">Избранное:</h2>
    {% include 'partial/reviews_list.html' %}
{% endblock %}